Develop
GodKIM91/TestGuru pull request #20
Opened 2022-03-01 17:34 UTC by GodKIM91

2022-03-02 07:24 UTC, BubuntuClu requested changes

2022-03-02 07:24 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :by_category, -> (category) { joins(:test).where(tests: { category: category }) }
у тебя есть этот метод в моделе тестов. стоит использовать его, вместо добавления того же самого кода в другую модель

2022-03-02 07:24 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def success_all_level?
стоит добавить параметр в метод чтобы он был более гибкий. допустим какой-то уровень тестов ты не хочешь вознаграждать или за какую-то категорию не хочешь выдавать бейдж. тогда параметр поможет тебе решить эту проблему

2022-03-02 07:24 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def completed_levels(user, level)
а зачем это выносить в метод? он больше нигде не переиспользуется

2022-03-02 07:24 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    category = Category.find_by(title: @test.category.title)
1 - ты знаешь операцию `join`, так что надо переделать с ее использованием
2 - у тебя уже есть метод в тестах, который делает практически то что тебе надо. используй его

2022-03-02 07:24 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    user.test_passages.by_passed.by_level(level).group(:test).count.keys.size
`.group(:test).count.keys.size` как ту все сложно. это зачем так?

2022-03-02 07:24 UTC, BubuntuClu commented on app/views/admin/badges/_form.html.erb
> +      <%= form.select(:rule, [category_rule, first_try_rule, level_rule], prompt: true) %>
формирование массива опция для селектора можно вынести в хэлпер. и тут потом этот хэлпер вызывать

2022-03-02 07:24 UTC, BubuntuClu commented on db/seeds.rb
> +  { name: 'Без права на ошибку!', image: 'first_try', rule: 'success_on_first_try', parameter: 'Пройти любой тест с первой попытки' },
то что ты хранишь в `parameter` больше похоже на `description`. а в от в `parameter` предлагаю тебе хранить значения для баджа. какой уровень он проверяет. какую категорию проверяет

2022-03-03 16:15 UTC, GodKIM91 commented on app/models/test_passage.rb
> +  scope :by_category, -> (category) { joins(:test).where(tests: { category: category }) }
Может быть в модели тестов удалить скоуп by_category? Он нигде на данный момент не используется

2022-03-03 16:15 UTC, GodKIM91 commented on app/services/badge_service.rb
> +  def success_all_level?
добавил ко всем методам

2022-03-03 16:15 UTC, GodKIM91 commented on app/services/badge_service.rb
> +  def completed_levels(user, level)
просто хотел сократить длинное равенство выше, чтоб строка не была чрезмерно длинной

2022-03-03 16:15 UTC, GodKIM91 commented on app/services/badge_service.rb
> +    category = Category.find_by(title: @test.category.title)
исправил

2022-03-03 16:15 UTC, GodKIM91 commented on app/services/badge_service.rb
> +    user.test_passages.by_passed.by_level(level).group(:test).count.keys.size
переделал на select(:test_id).distinct.size, стало чуть проще)

2022-03-03 16:16 UTC, GodKIM91 commented on app/views/admin/badges/_form.html.erb
> +      <%= form.select(:rule, [category_rule, first_try_rule, level_rule], prompt: true) %>
исправил, даже без хелпера обошелся

2022-03-03 16:16 UTC, GodKIM91 commented on db/seeds.rb
> +  { name: 'Без права на ошибку!', image: 'first_try', rule: 'success_on_first_try', parameter: 'Пройти любой тест с первой попытки' },
исправил

2022-03-04 09:04 UTC, BubuntuClu requested changes

2022-03-04 09:04 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def success_on_first_try?(param)
Тут параметр не нужен. У тебя же любой тест. Получается на каждый тест тебе надо создать Бадж по твоей логике, а это долго.

2022-03-04 09:04 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    category = Category.joins(:tests).where(:tests => {:title => @test.title})
Эм. Ты что-то не то делаешь. У тебя есть метод поиска тестов по имени категории. Используй его. Ты проблему не решил, ты всё так же делаешь лишний запрос в бд. Join ты используешь не так как я планировал. Param тут имя категории тесты которой тебе надо найти

2022-03-04 09:04 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @test_passages = @user.test_passages
Это вроде лишняя переменная

2022-03-04 09:04 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :by_passed, -> { where(passed: true) }
Нейминг скоупа смущает. Сделай просто passed.

2022-03-04 09:50 UTC, GodKIM91 commented on app/services/badge_service.rb
> +  def success_on_first_try?(param)
Убрал

2022-03-04 09:52 UTC, GodKIM91 commented on app/services/badge_service.rb
> +    @test_passages = @user.test_passages
убрал

2022-03-04 09:52 UTC, GodKIM91 commented on app/models/test_passage.rb
> +  scope :by_passed, -> { where(passed: true) }
готово

2022-03-04 12:49 UTC, GodKIM91 commented on app/services/badge_service.rb
> +    category = Category.joins(:tests).where(:tests => {:title => @test.title})
кажется, понял)

2022-03-05 07:34 UTC, BubuntuClu approved these changes

2022-03-05 07:34 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def success_on_first_try?(*test_title)
если параметр не используется его помечают нижней чертой `_param`

2022-03-05 12:16 UTC, merged